import HeroBanner from "@/components/HeroBanner"
import Highlights from "@/components/Highlights"
import Head from "next/head"
import { GetServerSideProps } from "next"
import Navbar from "@/components/Navbar"
import Categories from "@/components/Categories"
import { fetchAPI } from "@/utils"
import { HighlightType } from "@/utils"
import { CategoryType } from "@/utils"

const Home: React.FC<{ highlights: HighlightType[], categories: CategoryType[] }> = ({ highlights, categories }) => {

  return (
    <main className="flex min-h-screen w-full flex-col items-center justify-between font-IBM-Plexo">
      <Head>
        <title>Aloha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar highlights={highlights}/>
      <HeroBanner />
      <Highlights highlights={highlights} />
      <Categories categories={categories} />
    </main>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const highlights = await fetchAPI('highlights')
  const categories = await fetchAPI('categories')
  return {
    props: { highlights, categories }
  }
}
